name: TurfWar
version: 0.0.1
description: TurfWar Minigame Plugin
authors: [Dradraen, JosephCW]
main: com.github.dradraen.turfwar.Main

commands:
  turfwar:
    description: Base TurfWar Command
    aliases: [tw]
    usage: /<command>
  turfwar create:
    description: Create a new arena at these cords
    usage: /<command> <x1> <z1> <x2> <z2>